config/routes.rb
Rickrockstar::Application.routes.draw do
  resources :settings

  resources :question_sets
  match 'dashboard' => 'dashboard#index'

  mount Refinery::Core::Engine, :at => '/'

end

app/models/question_set.rb
class QuestionSet < ActiveRecord::Base
  attr_accessible :api_id, :private, :set_id
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :color_background, :color_footer, :color_top, :footer, :logo, :sitename

  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def set_headers
    response.headers['X-XSS-Protection'] = "0"
  end
  
	private
	  def logged_in
	  	if refinery_user? == false
	  		redirect_to refinery.new_refinery_user_session_path,
                    :flash => ({ :error => 'Sorry, you need to login to see this page.' })
	  	end
	  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :logged_in

	def index
		
	end
end

app/controllers/question_sets_controller.rb
class QuestionSetsController < ApplicationController
  before_filter :logged_in
  # GET /question_sets
  # GET /question_sets.json
  def index
    @question_sets = QuestionSet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @question_sets }
    end
  end

  # GET /question_sets/1
  # GET /question_sets/1.json
  def show
    @question_set = QuestionSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question_set }
    end
  end

  # GET /question_sets/new
  # GET /question_sets/new.json
  def new
    @question_set = QuestionSet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question_set }
    end
  end

  # GET /question_sets/1/edit
  def edit
    @question_set = QuestionSet.find(params[:id])
  end

  # POST /question_sets
  # POST /question_sets.json
  def create
    @question_set = QuestionSet.new(params[:question_set])

    respond_to do |format|
      if @question_set.save
        format.html { redirect_to @question_set, notice: 'Question set was successfully created.' }
        format.json { render json: @question_set, status: :created, location: @question_set }
      else
        format.html { render action: "new" }
        format.json { render json: @question_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /question_sets/1
  # PUT /question_sets/1.json
  def update
    @question_set = QuestionSet.find(params[:id])

    respond_to do |format|
      if @question_set.update_attributes(params[:question_set])
        format.html { redirect_to @question_set, notice: 'Question set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_sets/1
  # DELETE /question_sets/1.json
  def destroy
    @question_set = QuestionSet.find(params[:id])
    @question_set.destroy

    respond_to do |format|
      format.html { redirect_to question_sets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/refinery/sessions_controller.rb
module Refinery
  class SessionsController < Devise::SessionsController
    helper Refinery::Core::Engine.helpers
    layout 'refinery/layouts/login'

    before_filter :clear_unauthenticated_flash, :only => [:new]

    def create
      self.resource = warden.authenticate!(auth_options)
      set_flash_message(:notice, :signed_in) if is_navigational_format?
      sign_in(resource_name, resource)
      #respond_with resource, :location => after_sign_in_path_for(resource)
      redirect_to '/dashboard'
    rescue ::BCrypt::Errors::InvalidSalt, ::BCrypt::Errors::InvalidHash
      flash[:error] = t('password_encryption', :scope => 'refinery.users.forgot')
      redirect_to refinery.new_refinery_user_password_path
    end

  protected

    # We don't like this alert.
    def clear_unauthenticated_flash
      if flash.keys.include?(:alert) and flash.any?{|k, v|
        ['unauthenticated', t('unauthenticated', :scope => 'devise.failure')].include?(v)
      }
        flash.delete(:alert)
      end
    end

  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.first

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render json: @setting, status: :created, location: @setting }
      else
        format.html { render action: "new" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])

    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  	def get_settings
    default_color = "#e7e4d8"
		settings = Setting.new
		settings = Setting.first unless Setting.first.nil?
  		settings.sitename = 'Default' unless settings.sitename.present? 
  		settings.color_top = default_color unless settings.color_top.present? 
  		settings.color_background = default_color unless settings.color_background.present? 
  		settings.color_footer = default_color unless settings.color_footer.present?
      settings.footer = 'Footer Message Here...' unless settings.footer.present?
  		settings.logo = 'image/here' unless settings.logo.url.present?
  		return settings
  	end
	
  def page_layout(page) 
      if page.content_for(:side_body).present?
      return "<div class='span8'>
              #{raw page.content_for(:body)}
            </div>
            <div class='span4'>
              #{raw page.content_for(:side_body)}
            </div>"
      else
      return "<div class='span12'>
              #{raw page.content_for(:body)}
            </div>"
      end
  end	
  
  def logout_login
    if current_refinery_user.present?
     return link_to 'Log Out',
                    refinery.destroy_refinery_user_session_path, :id => 'logout'
    else 
      return link_to 'Sign In',
                    refinery.new_refinery_user_session_path, :id => 'login'
    end
  end

	def admin_or_client_adviser?
		if current_refinery_user.id == 1 || current_refinery_user.id == 2
			return true
		else
			return false
		end
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper


end

app/helpers/question_sets_helper.rb
module QuestionSetsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper


	def color_field(f, field, value, target) 
		if ( value != nil ) 
			color = value
		else 
			color = "rgb(0, 0, 0)"
		end

		return "    
			<div id=\"#{target}\" class=\"input-append color\" data-color=\"#{color}\" data-color-format=\"hex\">
      			#{ f.text_field field, :readonly => true, class: target }
      			<span class=\"add-on\"><i class=\"#{target}\" style=\"background-color: #{color}\"></i></span>
    		</div>"
	end
end

app/views/dashboard/index.html.erb
<div class="span12">
	<h1 class="text-center">Dashboard</h1>
	<div class="row-fluid">
		<% if admin_or_client_adviser? %>
		<div class="span3 well">
			<h2>CMS</h2>
			<p>
				Manage the Pages on your Site
			</p>
			<p>
				<a class="btn" href="/refinery">View details »</a>
			</p>
		</div>
		<div class="span3 well">
			<h2>Setttings</h2>
			<p>
				Manage colors, logo, etc
			</p>
			<p>
				<a class="btn" href="/settings">View details »</a>
			</p>
		</div>
		<% end %>
		<div class="span3 well">
			<h2>Question Sets</h2>
			<p>
				Manage the Questions Sets
			</p>
			<p>
				<a class="btn" href="/question_sets">View details »</a>
			</p>
		</div>
		<div class="span3 well">
			<h2>Reports</h2>
			<p>
				See the results of your tests
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= render '/refinery/html_tag' %>
  <% site_bar = render('/refinery/site_bar', :head => true) -%>
  <%= render '/refinery/head' %>
  <body style="background-color: <%= get_settings.color_background %>;">
    <!--keep sidebar out of html if not logged in-->
    <% if current_refinery_user.present? %>
    <div class="sitebar navbar">
      <%= site_bar -%>
      <%= render '/refinery/ie6check' if request.env['HTTP_USER_AGENT'] =~ /MSIE/ -%>
    </div>    
    <% end %>
    <div class="container-narrow">
      <!--top menu row-->
      <%= render '/refinery/header' -%>
      <div class="row content">
        <%= yield %>
      </div>
      <footer class="row" style="background-color: <%= get_settings.color_footer %>;">
        <%= render '/refinery/footer' -%>
      </footer>
    </div>
    <%= render '/refinery/javascripts' %>
  </body>
</html>

app/views/question_sets/_form.html.erb
<%= form_for(@question_set) do |f| %>
  <% if @question_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_set.errors.count, "error") %> prohibited this question_set from being saved:</h2>

      <ul>
      <% @question_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :set_id %><br />
    <%= f.number_field :set_id %>
  </div>
  <div class="field">
    <%= f.label :api_id %><br />
    <%= f.number_field :api_id %>
  </div>
  <div class="field">
    <%= f.label :private %><br />
    <%= f.check_box :private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_sets/edit.html.erb
<h1>Editing question_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_set %> |
<%= link_to 'Back', question_sets_path %>

app/views/question_sets/index.html.erb
<div ng-app="FIS">
    <div ng-controller="QandACtrl">
    <h1>Listing question_sets</h1>
    <p>Below is a list of questions from the API. Please choose the ones you would like to use to make your set</p>

    <h2>Choose your questions from the API</h2>
    <!-- click on the items in the list to push into the chosen array -->

    <ul>
      <li ng-repeat="question in questionsAPI">
        {{question.Short}}
      </li>
    </ul>

    <!-- show items from chosen array -->
    {{questionsAPI}}

    <h1>Your Question Set</h2>
    <div ng-controller="QandACtrl">
      <form>
        <input type="text" ng-model="set.name" placeholder="Set Name..."></br>
        <input type="text" name="id" ng-model="set.id" size="4" value="" disabled/>
        
        <input type="text" ng-repeat="set_question set_questions" value="" disabled/>


        <br>
        <button>Save Set</button>
      </form>

      
    </div>



    <!-- original code -->
    <table>
      <tr>
        <th>Set</th>
        <th>Api</th>
        <th>Private</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @question_sets.each do |question_set| %>
      <tr>
        <td><%= question_set.set_id %></td>
        <td><%= question_set.api_id %></td>
        <td><%= question_set.private %></td>
        <td><%= link_to 'Show', question_set %></td>
        <td><%= link_to 'Edit', edit_question_set_path(question_set) %></td>
        <td><%= link_to 'Destroy', question_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />
  </div>
  <%= link_to 'New Question set', new_question_set_path %>
</div>

app/views/question_sets/new.html.erb
<h1>New question_set</h1>

<%= render 'form' %>

<%= link_to 'Back', question_sets_path %>

app/views/question_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Set:</b>
  <%= @question_set.set_id %>
</p>

<p>
  <b>Api:</b>
  <%= @question_set.api_id %>
</p>

<p>
  <b>Private:</b>
  <%= @question_set.private %>
</p>


<%= link_to 'Edit', edit_question_set_path(@question_set) %> |
<%= link_to 'Back', question_sets_path %>

app/views/refinery/_content_page.html.erb
<%= render_content_page(@page, {
      :hide_sections => local_assigns[:hide_sections],
      :can_use_fallback => !local_assigns[:show_empty_sections] && !local_assigns[:remove_automatic_sections]
    }) %>

<%= render '/refinery/draft_page_message' unless @page.nil? or @page.live? -%>

app/views/refinery/_footer.html.erb
<div class="span12">
	<%= raw get_settings.footer %>
</div>

app/views/refinery/_head.html.erb
<head>
  <meta charset='<%= Rails.application.config.encoding %>' />
  <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" /><![endif]-->
  <title><%= get_settings.sitename %></title>
  <%= raw %(<meta name="description" content="#{@meta.meta_description}" />) if @meta.meta_description.present? -%>
  <%= raw %(<meta name="keywords" content="#{@meta.meta_keywords}">) if @meta.meta_keywords.present? -%>
  <%= raw %(<link rel="canonical" content="#{@canonical}" />) if @canonical.present? -%>
  <%= csrf_meta_tags if Refinery::Core.authenticity_token_on_frontend -%>
  <%= yield :meta %>

  <%= stylesheet_link_tag "application", "formatting", "theme" %>
  <%= stylesheet_link_tag "home" if home_page? %>
  <%= yield :stylesheets %>

  <%= render '/refinery/google_analytics' %>

  <%= javascript_include_tag 'modernizr-min' %>
</head>

app/views/refinery/_header.html.erb
<%= render(:partial => "/refinery/menu", :locals => {
             :dom_id => 'menu',
             :css => 'menu'
           }) %>

app/views/refinery/_menu.html.erb
<%

  color_top = get_settings.color_top
  image_top = get_settings.logo

  # Collect the root items.
  # ::Refinery::Menu is smart enough to remember all of the items in the original collection.
  if (roots = local_assigns[:roots] || (collection ||= refinery_menu_pages).roots).present?
    dom_id ||= 'menu'
    css = [(css || 'menu clearfix')].flatten.join(' ')
    hide_children = Refinery::Core.menu_hide_children if hide_children.nil?
-%>

  <div class="top-area-wrapper row" style="background-color: <%= color_top %>; background-image: none; border-color: <%= color_top %>;">
      <%= link_to image_tag(image_top, :border=>0), refinery.root_path, :class => 'brand span5' %>
      
      <div class="menu navbar span6 pull-right">
        <div class="navbar-inner">
          <ul class="nav">
            <%= render :partial => '/refinery/menu_branch', :collection => roots,
                       :locals => {
                         :hide_children => hide_children,
                         :sibling_count => (roots.length - 1),
                         :menu_levels => local_assigns[:menu_levels],
                         :apply_css => true #if you don't care about class='first' class='last' or class='selected' set apply_css to false for speed.
                       } -%>
            <li><%= logout_login %>
          </ul>
      </div>
    </div>
  </div>
<% end -%>

app/views/refinery/_menu_branch.html.erb
<%
  if !!local_assigns[:apply_css] and (classes = menu_branch_css(local_assigns)).any?
    css = "class='#{classes.join(' ')}'".html_safe
  end
-%>
<li<%= ['', css].compact.join(' ').gsub(/\ *$/, '').html_safe %>>
<%= link_to(menu_branch.title, refinery.url_for(menu_branch.url)) -%>
  <% if ( (children = menu_branch.children unless hide_children).present? &&
          (!local_assigns[:menu_levels] || menu_branch.ancestors.length < local_assigns[:menu_levels]) ) -%>
    <ul class='clearfix'>
      <%= render :partial => '/refinery/menu_branch', :collection => children,
                 :locals => {
                   :apply_css => local_assigns[:apply_css],
                   :hide_children => !!hide_children,
                   :menu_levels => local_assigns[:menu_levels]
                 } -%>
    </ul>
  <% end -%>
</li>

app/views/refinery/_site_bar.html.erb
<% if refinery_user? && "#{controller_name}##{action_name}" != 'pages#preview' %>
  <% unless admin? # all required JS included by backend. %>
    <% content_for :stylesheets, stylesheet_link_tag('refinery/site_bar') unless !!local_assigns[:exclude_css] %>
    <%= yield(:stylesheets) unless local_assigns[:head] or local_assigns[:exclude_css] %>
  <% end -%>
  <div id='site_bar'>
    <div id='site_bar_content' class='clearfix'>
      <div id='editor_switch'>
        <%= link_to "Dashboard", '/dashboard', :class => 'btn btn-info' %>
      </div>

      <div id='site_bar_branding'>
        <%= link_to 'Home', '/' %> &nbsp; &nbsp;| 
        <%= link_to t('.log_out', site_bar_translate_locale_args),
                    refinery.destroy_refinery_user_session_path, :id => 'logout' %>
      </div>
    </div>
  </div>
<% end %>

app/views/refinery/pages/home.html.erb
<%= raw page_layout(@page) %>

app/views/refinery/pages/show.html.erb
<h1><%= @page.title %></h1>
<hr>
<%= raw page_layout(@page) %>

app/views/settings/_fields.html.erb
<p>
  <b>Site Name:</b>
  <%= setting.sitename %>
</p>
<p>
  <b>Color top:</b>
  <%= setting.color_top %>
</p>

<p>
  <b>Color footer:</b>
  <%= setting.color_footer %>
</p>

<p>
  <b>Color background:</b>
  <%= setting.color_background %>
</p>

<p>
  <b>Footer:</b>
  <%= raw setting.footer %>
</p>

<p>
  <b>Logo:</b>
  <img src="<%= setting.logo.url(:medium) %>">
</p>

app/views/settings/_form.html.erb
<div class="span5">
<%= form_for @setting, :html => { :multipart => true } do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :sitename %><br />    
    <%= f.text_field :sitename %>
  </div>
  <div class="field">
    <%= f.label :color_top %><br />    
    <%= raw color_field(f, :color_top, @setting.color_top, 'top') %>
  </div>
  <div class="field">
    <%= f.label :color_footer %><br />
    <%= raw color_field(f, :color_footer, @setting.color_footer, 'footer') %>
  </div>
  <div class="field">
    <%= f.label :color_background %><br />
    <%= raw color_field(f, :color_background, @setting.color_background, 'background') %>
  </div>
  <div class="field">
    <%= f.label :footer %><br />
    <%= f.text_area :footer, rows: 10 %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.file_field :logo %>
    <span class="help-block">Image size: 70px tall and about 400px wide is a good size.</span>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

<div>
  <p><strong>Set your branding here. Below is some lorem ipsum text to get a sense of the end result</strong></p>
  <div>
    Bacon ipsum dolor sit amet doner tri-tip hamburger corned beef. Tail kielbasa pork chop cow ham hock biltong, tri-tip brisket pig short loin fatback t-bone filet mignon tenderloin pork loin. Ham hock rump meatloaf, bacon short loin tongue strip steak beef cow filet mignon ground round frankfurter. Sausage strip steak corned beef, tenderloin sirloin swine ground round t-bone frankfurter pancetta kielbasa pork drumstick.

    Pork chicken ball tip ham jowl venison shoulder boudin turkey sirloin corned beef tri-tip. Ham short ribs tail ground round. Frankfurter pork chop shoulder shank ham hock shankle fatback capicola bacon bresaola pastrami ball tip andouille beef ribs. Ham hock corned beef swine, frankfurter hamburger shank pork loin doner fatback rump jerky beef prosciutto meatball chuck. Turkey swine biltong boudin brisket pig ham hock chuck corned beef meatloaf.

    Drumstick swine doner rump meatball. Beef ball tip pork loin sirloin doner, tri-tip pancetta strip steak brisket venison chicken shankle rump ground round. Frankfurter pork loin tail kielbasa doner t-bone sausage ground round meatloaf venison tongue bresaola. Meatball venison pastrami sirloin. Pastrami turkey tenderloin pig pork belly. Salami ball tip leberkas pork loin shankle pig. Bacon chuck tail t-bone beef tenderloin venison pastrami drumstick capicola frankfurter jowl tri-tip pig ribeye.
  </div>
</div>

app/views/settings/edit.html.erb
<h2>Editing setting</h2>

<%= render 'form' %>

app/views/settings/index.html.erb
<h1>Settings</h1>
<div class="settings-container">
    <div class="span6 offset1">
        <br>
        <br>
        <br>
        <% if Setting.count() == 0 %>
            <%= link_to 'Customize Settings', new_setting_path, class: "btn" %>
        <% else %>
        <%= render :partial => 'fields', :locals => { :setting => @settings } %>

        <%= link_to 'Edit Settings', edit_setting_path(@settings), class: "btn" %>

        <% end %>
    </div>
</div>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => 'fields', :locals => { :setting => @setting } %>

<%= link_to 'Edit', edit_setting_path(@setting), :class => 'btn btn-info' %>